version: '3'
services: 
  db:
    image: mysql:latest
    container_name: dbserver
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: sample
      MYSQL_DATABASE: helpdesk
      MYSQL_USER: helpdesk
      MYSQL_PASSWORD: abcd
  tomcat:
    image: tomcat:latest
    container_name: appserver
    ports:
      - "80:8080"
    links:
      - db

